// Generates src/data/words.js (narration word timings) and src/data/geo.js (coastlines/borders)
// from assets/scenario.json and the public-domain Natural Earth data in the world-atlas package.
const fs = require('fs');
const path = require('path');
const topojson = require('topojson-client');

const root = path.join(__dirname, '..');
const scenario = JSON.parse(fs.readFileSync(path.join(root, 'assets/scenario.json'), 'utf8'));
const words = [];
for (const s of scenario.segments) for (const w of s.words) {
  words.push([w.word.trim().toLowerCase().replace(/[^a-z0-9.']/g, ''), +w.start.toFixed(2), +w.end.toFixed(2)]);
}
fs.writeFileSync(path.join(root, 'src/data/words.js'),
  '// Auto-generated by tools/prepare-data.js — [word, start, end] in narration seconds\n' +
  'export const WORDS = ' + JSON.stringify(words) + ';\n');

function rings(geom) {
  if (!geom) return [];
  if (geom.type === 'Polygon') return geom.coordinates;
  if (geom.type === 'MultiPolygon') return geom.coordinates.flat();
  return [];
}
function ringArea(r) { let a = 0; for (let i = 0; i < r.length; i++) { const [x1, y1] = r[i], [x2, y2] = r[(i + 1) % r.length]; a += x1 * y2 - x2 * y1; } return Math.abs(a / 2); }
function simplify(r, tol) {
  // radial distance simplification, keeps shape good enough for textures
  const out = [r[0]]; let last = r[0];
  for (let i = 1; i < r.length; i++) { const p = r[i]; if (Math.hypot(p[0] - last[0], p[1] - last[1]) >= tol) { out.push(p); last = p; } }
  return out;
}
const q = (v, d) => +v.toFixed(d);

// Globe land (50m, simplified)
const land50 = JSON.parse(fs.readFileSync(require.resolve('world-atlas/land-50m.json')));
const landGeo = topojson.feature(land50, land50.objects.land);
const globeLand = [];
for (const f of (landGeo.features || [landGeo])) for (const r of rings(f.geometry)) {
  if (ringArea(r) < 0.6) continue;
  const s = simplify(r, 0.35).map(p => [q(p[0], 1), q(p[1], 1)]);
  if (s.length > 3) globeLand.push(s);
}

// Region (lon 18..56, lat 24..48): country polygons with names, higher detail
const c50 = JSON.parse(fs.readFileSync(require.resolve('world-atlas/countries-50m.json')));
const countries = topojson.feature(c50, c50.objects.countries);
const BB = [14, 22, 60, 50];
const region = [];
for (const f of countries.features) {
  const rs = rings(f.geometry).filter(r => r.some(([x, y]) => x >= BB[0] && x <= BB[2] && y >= BB[1] && y <= BB[3]));
  if (!rs.length) continue;
  const polys = rs.filter(r => ringArea(r) > 0.004).map(r => simplify(r, 0.04).map(p => [q(p[0], 3), q(p[1], 3)]));
  if (polys.length) region.push({ name: f.properties.name, rings: polys });
}
// region land outline (coastline) from land-50m
const regionLand = [];
for (const f of (landGeo.features || [landGeo])) for (const r of rings(f.geometry)) {
  if (!r.some(([x, y]) => x >= BB[0] && x <= BB[2] && y >= BB[1] && y <= BB[3])) continue;
  if (ringArea(r) < 0.004) continue;
  regionLand.push(simplify(r, 0.03).map(p => [q(p[0], 3), q(p[1], 3)]));
}
fs.writeFileSync(path.join(root, 'src/data/geo.js'),
  '// Auto-generated by tools/prepare-data.js from Natural Earth (public domain) via world-atlas\n' +
  'export const GLOBE_LAND = ' + JSON.stringify(globeLand) + ';\n' +
  'export const REGION_COUNTRIES = ' + JSON.stringify(region) + ';\n' +
  'export const REGION_LAND = ' + JSON.stringify(regionLand) + ';\n');
console.log('words', words.length, 'globe rings', globeLand.length, 'region countries', region.length, region.map(r => r.name).join(', '));
